export const MODEL_ASSETS = {
    cottageHouse: new URL('../../assets/models/cottage-house.glb', import.meta.url).href,
    supermarketStore: new URL('../../assets/models/supermarket-store.glb', import.meta.url).href,
    schoolClocktower: new URL('../../assets/models/school-clocktower.glb', import.meta.url).href,
    marketStall: new URL('../../assets/models/market-stall.glb', import.meta.url).href,
    cornerCafe: new URL('../../assets/models/corner-cafe.glb', import.meta.url).href,
    cafeTerrace: new URL('../../assets/models/cafe-terrace.glb', import.meta.url).href,
    marketDecor: new URL('../../assets/models/market-decor.glb', import.meta.url).href,
    lakesideGazebo: new URL('../../assets/models/lakeside-gazebo.glb', import.meta.url).href,
    cottageYard: new URL('../../assets/models/cottage-yard.glb', import.meta.url).href,
    mainStreetRow: new URL('../../assets/models/main-street-row.glb', import.meta.url).href,
    streetDetailKit: new URL('../../assets/models/street-detail-kit.glb', import.meta.url).href,
    foregroundGarden: new URL('../../assets/models/foreground-garden.glb', import.meta.url).href,
    farmBarn: new URL('../../assets/models/farm-barn.glb', import.meta.url).href,
    taxiCab: new URL('../../assets/models/taxi-cab.glb', import.meta.url).href,
    townsperson: new URL('../../assets/models/townsperson.glb', import.meta.url).href,
    treeOak: new URL('../../assets/models/tree-oak.glb', import.meta.url).href,
    treePine: new URL('../../assets/models/tree-pine.glb', import.meta.url).href,
    bench: new URL('../../assets/models/bench.glb', import.meta.url).href,
    planter: new URL('../../assets/models/planter.glb', import.meta.url).href,
    waterTower: new URL('../../assets/models/water-tower.glb', import.meta.url).href,
    cloudPuff: new URL('../../assets/models/cloud-puff.glb', import.meta.url).href,
    mountainLakeSlice: new URL('../../assets/models/mountain-lake-slice.glb', import.meta.url).href,
};
